### ISSUE TITLE
[Bug] SPM package dependency with hyphenated name cannot be linked to test targets

### ISSUE THREAD

**Issue by kalub92** [trinhngocthuyen/cocoapods-spm#87] opened 2024-05-06 20:09 UTC
### What happened?

When attempting to compile the test target for my project, I get the following errors:

Error 1 (`SwiftDriver` error building `DependencyPackage-iOS`):
```
Module name "DependencyPackage-iOS" is not a valid identifier
```

Error 2 (building `PackageA`):
```
No such module 'DependencyPackage_iOS'
```

It seems that the hyphenated `DependencyPackage-iOS` is an invalid module name, but I notice in `PackageA` that when they've been importing this dependency as `DependencyPackage_iOS` with an underscore. Does `cocoapods-spm` account for this? 

I looked up the `Module name is not a valid identifier` error and saw that using hyphens in module names is not allowed but that there is a C99 modifier that can be used (e.g. `c99extidentifier `) when linking frameworks to allow this: `$(PRODUCT_NAME:c99extidentifier)`.

Wondering if this is part of the issue?

### Stack

```
   CocoaPods : 1.13.0
        Ruby : ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
    RubyGems : 3.3.3
        Host : macOS 14.3.1 (23D60)
       Xcode : 15.0 (15A240d)
         Git : git version 2.44.0
Ruby lib dir : /Users/cstultz/.rvm/rubies/ruby-3.1.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/cstultz/.rvm/gems/ruby-3.1.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-pod-linkage : 0.0.1
cocoapods-search      : 1.0.1
cocoapods-spm         : 0.1.4
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
slather               : 2.8.0
```

### Podfile

```ruby
require '../tools/cocoapods-utilities/Utilities.rb'
plugin 'cocoapods-pod-linkage'
plugin 'cocoapods-spm'

# Check for bundler
verify_bundler_was_used()

workspace 'FooWorkspace'
use_frameworks! :linkage => :dynamic
inhibit_all_warnings!
platform :ios, '16.0'
source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :disable_input_output_paths => true

def test_pods
  pod_module 'TestKit'
end

def spm_pods
  spm_pkg "PackageA",
          :url => "https://github.com/developer/PackageA.git",
          :version => "2.3.2",
          :linkage => :static,
          :linking => {
            # Prefer adding products to the "Link Binary With Libraries" section
            :use_default_xcode_linking => true,
            :linker_flags => ["-ld64"]
          }

  spm_pkg "PackageB",
          :url => "https://github.com/developer/PackageB.git",
          :version => "1.4.1",
          :linkage => :static
end

# You should NOT add or remove pods directly to the targets below! Use the methods above.
abstract_target 'Foo' do

  spm_pods
  
  target 'Bar' do
    project 'FooWorkspace', 'DebugTeam' => :debug, 'UnitTests' => :debug
  end

  target 'Bar Tests' do
    project 'FooWorkspace, 'DebugTeam' => :debug, 'UnitTests' => :debug
    test_pods
    pod 'Nimble', '~> 11.2.0'
    pod 'Quick', '~> 6.1.0'
    pod 'DGCharts', '5.0'
  end
  
end
```

**Comment by trinhngocthuyen** [comment] 2024-05-08 03:02
@kalub92 Actually, cocoapods-spm has nothing to do with the module name.
It's up to the package author to manage it. Linking frameworks/libraries/packages does not intervene in how the module name is treated.

If the target name is `foo-ios`, for example, then the module name is `foo_ios`.
```rb
let package = Package(
  ...
  targets: [
    .target(name: "foo-ios") // <-- HERE
  ]
)
```

(1) Therefore, please first make sure you're using the correct module name in Swift code: `import foo_ios`

(2) In case you're specifying the correct module name `foo_ios` and it's still saying `No such module 'foo_ios'`, it might be a linking issue (potentially caused by this plugin).
In this case, is it possible to have a demo to reproduce the issue? (you can use the [example project](https://github.com/trinhngocthuyen/cocoapods-spm/tree/main/examples) for convenience)

Thank you!

**Comment by kalub92** [comment] 2024-05-08 04:38
Thanks for the clarification! The package is defined with the name `PackageName-iOS` and shows up in Xcode like this: `import PackageName_iOS` but I'm still seeing the `No such module...` errors.

I'll try to get a sample project to you tomorrow to investigate! Thank you!

**Comment by kalub92** [comment] 2024-05-08 23:08
I was able to reproduce this! I created a new sample module called `SamplePackageB-iOS` (only difference is a hyphenated name) and created a branch off of `SamplePackageA` that consumes this package instead of the previous module, `SamplePackageB`.

I forked `cocoapods-spm` and the example project demonstrates this issue on this branch: [kalub92/hyphenated_module_name_bug](https://github.com/kalub92/cocoapods-spm/tree/kalub92%2Fhyphenated_module_name_bug)

I am consuming my module like so in an abstract target (like the app I'm trying to resolve this for):

```ruby
def spm_pods
  spm_pkg "SamplePackageA",
          :git => "https://github.com/kalub92/SamplePackageA.git",
          :branch => "withHyphenatedDependency",
          :linkage => :static,
          :linking => {
            # Prefer adding products to the "Link Binary With Libraries" section
            :use_default_xcode_linking => true,
            :linker_flags => ["-ld_classic"]
          }
end

abstract_target 'Example' do

  spm_pods

  target "EX" do
    pod "Logger", :path => "LocalPods/Logger"
    # pod "CommonUI", :path => "LocalPods/CommonUI"
    # pod "Services", :path => "LocalPods/Services"

    spm_pkg "SnapKit",
            :url => "https://github.com/SnapKit/SnapKit.git",
            :version => "5.7.1",
            :products => ["SnapKit-Dynamic"]
    spm_pkg "SwiftUIX", :git => "https://github.com/SwiftUIX/SwiftUIX.git", :tag => "0.1.9"
    spm_pkg "SwiftyBeaver", :git => "https://github.com/SwiftyBeaver/SwiftyBeaver.git", :tag => "2.0.0"
    spm_pkg "opentelemetry-swift",
            :git => "https://github.com/open-telemetry/opentelemetry-swift.git",
            :branch => "main",
            :products => ["OpenTelemetrySdk"]
    spm_pkg "GoogleMaps",
            :git => "https://github.com/googlemaps/ios-maps-sdk.git",
            :version => "8.4.0",
            :products => ["GoogleMaps", "GoogleMapsBase", "GoogleMapsCore"]
    spm_pkg "DebugKit", :path => "LocalPackages/debug-kit"
  end
  
  target "EXTests" do

  end
end
```

> FYI, I removed a few dependencies because there was a compilation error related to `Orcam` that was preventing me from compiling the project.

The `pod install` command executes successfully, but when I attempt to run either the `EX` or `EX Tests` targets, I see this error related to the `[CP] Copy Pods Resources` build phase:

![Screenshot 2024-05-08 at 3 36 30 PM](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/ab6cb8d4-88b5-4f58-8e42-003c906aa408)

To see if I could get around that, I deleted that phase manually from both `EX` and `EX Tests` targets.

When attempting to compile `EX` target, I get a duplicate symbols error ([gist](https://gist.github.com/kalub92/faa728b9d4d6250ed884cf6b35c431a6)):
![Screenshot 2024-05-08 at 4 01 11 PM](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/c3d5d15b-d4fc-4f81-9e82-a68945eaa8ed)

When attempting to compile the `EX Tests` target, I see that mentioned hyphenated `No module found...` naming issue: 
![Screenshot 2024-05-08 at 3 35 38 PM](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/f3d2d6fc-2f3b-4336-bc2f-728b9f715b86)

**Comment by trinhngocthuyen** [comment] 2024-05-09 07:39
Thanks for the reproduction.
I managed to make it work on this branch: [demo/87](https://github.com/trinhngocthuyen/cocoapods-spm/tree/demo/87). Kindly check [this commit](https://github.com/trinhngocthuyen/cocoapods-spm/commit/f9890adf792a2c531d4dbf5ff9877f24699502d3) for the diff.

Highlights of the change:
- Please do not add the same package to the main target. If a package is declared in Podfile (for `Pods-<App>`), it's already usable for the `<App>` target.
As a best practice, you should not have any SPM added to the App's xcodeproj.
- Removed the `:use_default_xcode_linking => true` option.
  - With the Xcode's default linking, I don't really know why but the linker doesn't work well despite using the `-ld_classic` argument, causing the duplicate symbols :(.
  - Various improvements have been added to the xcconfig-based linking strategy already :). So, I'd recommend removing this `:use_default_xcode_linking` option.

**Comment by kalub92** [comment] 2024-05-10 20:01
I made the changes you suggested:
* Did not add the same package to the main target
* Removed all `.xcodeproj` SPM packages and defined in Podfile instead
* Removed usage of `:use_default_xcode_linking`

This does resolve the `No such module`/`Module name is not a valid identifier` error, but now I'm seeing this in my project at work:

```bash
Missing required module '3rdPartyAdapter'
```

Which is a recursive dependency of the main SPM package I'm trying to import:

```bash
SamplePackageA
     ↳ SamplePackageB-iOS
          ↳ 3rdPartyAdapter
```

I'm working on reproducing this in the sample app project, but haven't had luck yet...

**Comment by kalub92** [comment] 2024-05-10 20:30
I was able to reproduce it in the sample project: [link](https://github.com/kalub92/cocoapods-spm/tree/kalub92%2Fhyphenated_module_name_bug)

After closer inspection, I made changes to the following modules to more closely follow the pattern established in our app:

* `SamplePackageA (branch: withHyphenatedDependency)` ([3 commits](https://github.com/kalub92/SamplePackageA/commits/withHyphenatedDependency/?since=2024-05-09&until=2024-05-10))
* `SamplePackageB-iOS` ([4 commits](https://github.com/kalub92/SamplePackageB-iOS/commits/master/?since=2024-05-09&until=2024-05-10))

When compiling, I first see this referencing the `[CP] Copy Pods Resources` build phase:
![image](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/984c96e9-47a1-472f-a081-4a4262fc5abd)

Then, after removing that from `EX`/`EX Tests`, attempting to compile results in the error I see in my work project:
![image](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/3c009344-193d-4e61-85b8-bf578a7bade8)

**Comment by trinhngocthuyen** [comment] 2024-05-11 03:06
I checked out the demo code at the given commit [88f6b6e](https://github.com/kalub92/cocoapods-spm/commit/88f6b6e443aaaadff41a79b76259a2e455f802b9).

Below is the revision of the packages:
<img width="479" alt="Screenshot 2024-05-11 at 09 51 43" src="https://github.com/trinhngocthuyen/cocoapods-spm/assets/8844044/e9a2b4a4-3ecd-44f1-aade-9755550b8460">

As I mentioned in the earlier comment, the _"multiple commands produce..."_ error is because **the same package was added to the main target** (which is duplicated). Because this step fails, the subsequent steps might produce false-alarm errors.

<img width="600" alt="Screenshot 2024-05-11 at 09 34 50" src="https://github.com/trinhngocthuyen/cocoapods-spm/assets/8844044/54dab870-949d-43e7-9940-af9d292efc8e">

<img width="600" alt="Screenshot 2024-05-11 at 09 34 59" src="https://github.com/trinhngocthuyen/cocoapods-spm/assets/8844044/79674953-d440-4bc6-b590-515b1a1100ba">

Please remove the package from the main target because the package is transitively available when adding it to the Pods project already.

After removing it, the build succeeded from my end.
<img width="600" alt="Screenshot 2024-05-11 at 09 48 41" src="https://github.com/trinhngocthuyen/cocoapods-spm/assets/8844044/4c7a82ad-69d7-42c2-abbf-031adad1829f">

Do let me know if I missed any steps :)

**Comment by kalub92** [comment] 2024-05-13 20:14
Thanks for the reply! I just removed `SamplePackageA` from the `EX` project, which removed it (and `SamplePackageAConfig`) from `Link Binary with Libraries` as you'd expect.

Commit: https://github.com/trinhngocthuyen/cocoapods-spm/commit/1fd8bccf77365ce78ac4304a4fd380bca82c1e19

And I don't get the `Multiple commands produce...` error anymore however, after cleaning the project and deleting derived data I still see the `Missing required module 'ThirdPartyAdapter'` error.
 
 ![image](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/24aea4a6-c6c6-4c4e-92a0-41aa03288500)

**Comment by kalub92** [comment] 2024-05-14 22:20
Another update: after reading a bit about others experiencing similar problems and found that they avoid exposing transitive dependencies to the developer by using static linkage and the `@_implementationOnly` modifier to import that dependency.

Even though this is an undocumented modifier, a few large frameworks (Firebase, for example), has been using this for a while: https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk+%40+_implementationOnly&type=code

It seems that this was formalized in Swift 6.0: https://github.com/apple/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md

Anyway, I made that change here and it resolved the `Missing required module` issue and allows the app target and test target to compile and run successfully:
https://github.com/kalub92/SamplePackageA/blob/6eea4f37ae112c4fb7efabc1b87183622599f84b/Sources/SamplePackageA/SamplePackageA.swift#L2

Not sure if this helps figure out why it isn't able to see `ThirdPartyAdapter`, but figured I'd share!

**Comment by kalub92** [comment] 2024-05-15 22:30
@trinhngocthuyen Strange... I did the following:
* Deleted the `.spm.pods` directory
* Deleted `DerivedData` & quit Xcode
* Ran `pod install`
* Opened Xcode and attempted to build

But I'm still seeing the same error.

**Comment by kalub92** [comment] 2024-05-16 16:55
Discovered why it was working on your end – I had made changes to the `SamplePackageA` and `SamplePackageB-iOS` which allowed compilation.

Just updated those packages back to their former settings they should have been at:

* https://github.com/kalub92/SamplePackageA/commit/ae8fa9e4a7bbddb541026a69a204dff15cd0a0c0
* https://github.com/kalub92/SamplePackageB-iOS/commit/5706724e1c6bc18410595c04110a713b30e0c03f

The behavior where the app target compiles successfully, but the test target does not is back with these changes.

I think it might have something to do with the `.mm` & `.hpp` files in `ThirdPartyAdapter`? It's an adapter that is supposed to work with the provided `.xcframeworks` in `Frameworks/ThirdPartyVendor/iOS`.

**Comment by trinhngocthuyen** [comment] 2024-05-17 12:21
Hi @kalub92,

PR #88 should fix the above issue. Kindly help verify with the latest from main.
Below are some more details:
- The issue is not about hyphenated names, but about C-family modules not getting recognized.
- The issue should not have occurred when we explicitly declared `publicHeadersPath: "foo"` in the target.
In this case, the package was using an implicit headers path (`<Target>/include`), a corner case the plugin has not yet handled.

Thank you for your collaborative effort! That means a lot :)

**Comment by kalub92** [comment] 2024-05-18 14:55
Thank you so much! This seems to have resolved the `Missing required module...` error but now that I've gotten past that I am seeing a bunch of `Undefined symbols...` errors from that adapter when attempting to link my podspec that takes in these packages as dependencies...

I'm seeing this in my work project, but I'm trying to configure my sample packages so that it reproduces the same behavior in the sample app.

**Comment by trinhngocthuyen** [comment] 2024-05-19 09:53
*"Undefined symbols..."* typically means there's a library/framework/object that was not linked to the binary.
May I know the undefined symbols? They should give us a clue about which binary was not linked.

**Comment by kalub92** [comment] 2024-05-20 19:31
I'm not able to share the particular symbols from my work project, but was able to reproduce this issue by adding some methods to the `ThirdPartyAdapter` to wrap around the provided `OneSignal.xcframework`:

![image](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/b4f8a8ec-7264-4692-b8b2-1ef4327205c4)


This structure very closely resembles how my work project is configured with this dependency.

Please check out the [latest commit](https://github.com/kalub92/cocoapods-spm/commit/44cf9ee0692d13744be30826653c1bad4e3fc0dd) for my fork and run the sample app and ensure that SamplePackageB-iOS is updated to its latest commit as well: https://github.com/kalub92/SamplePackageB-iOS/commit/064c476b28cdec893fcce53b09337f2dbc611f8a

**Comment by trinhngocthuyen** [comment] 2024-05-21 13:54
@kalub92 Would you mind checking again with the latest from main (fixed by https://github.com/trinhngocthuyen/cocoapods-spm/pull/93)? Thank you!

**Comment by kalub92** [comment] 2024-05-31 00:09
@trinhngocthuyen after pulling the latest and getting my fork up to date with your `main` branch, I realized I was missing some commits and after updating, I get this error in the post install steps for my work project (haven't reproduced it yet in the sample project):

```
NoMethodError - undefined method `slices' for nil:NilClass

          @binary_basename ||= xcframework.slices[0].path.basename.to_s
                                          ^^^^^^^
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/swift/package/target.rb:91:in `binary_basename'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/swift/package/target.rb:49:in `linker_flags'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/resolver/result.rb:48:in `each'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/resolver/result.rb:48:in `flat_map'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/resolver/result.rb:48:in `linker_flags_for'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/post_integrate/5.update_settings.rb:74:in `linker_flags_for'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/post_integrate/5.update_settings.rb:63:in `block in update_linker_flags'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:66:in `block in perform_settings_update'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:76:in `block (2 levels) in perform_settings_update'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:75:in `each'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:75:in `block in perform_settings_update'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:74:in `each'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:74:in `perform_settings_update'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/post_integrate/5.update_settings.rb:60:in `update_linker_flags'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/post_integrate/5.update_settings.rb:12:in `run'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:53:in `block (2 levels) in run_hooks'
/Users/cstultz/.rvm/gems/ruby-3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:149:in `message'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:52:in `block in run_hooks'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:48:in `each'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/hooks/base.rb:48:in `run_hooks'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/patch/installer.rb:53:in `run_spm_post_integrate_hooks'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bundler/gems/cocoapods-spm-a63447cff3da/lib/cocoapods-spm/patch/installer.rb:34:in `block in <class:Installer>'
/Users/cstultz/.rvm/gems/ruby-3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/Users/cstultz/.rvm/gems/ruby-3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/cstultz/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/cstultz/.rvm/gems/ruby-3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/cstultz/.rvm/gems/ruby-3.1.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bin/pod:25:in `load'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bin/pod:25:in `<main>'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
/Users/cstultz/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by kalub92** [comment] 2024-05-31 18:29
Updated my previous comment 👆

**Comment by kalub92** [comment] 2024-05-31 20:24
To validate that your fix above worked for the binary name detection and public headers issues I made a few other changes to more closely follow my app's structure:

* Removed our Firebase dependency temporarily

* Refactored `TestKit` into `NetworkTestKit` and `AppTestKit`, which in our code basically do the following:
  * `NetworkTestKit` takes in `SamplePackageA` as an SPM dependency
     ```ruby
      Pod::CompactSpec.new do |s|
         s.name = "NetworkTestKit"
         s.spm_dependency "SamplePackageA/SamplePackageA"
      end
     ```

  * `AppTestKit` takes in `NetworkTestKit` as a dependency
     ```ruby
      Pod::CompactSpec.new do |s|
          s.name = "AppTestKit"
          s.dependency "NetworkTestKit"
      end
     ```

* Made changes to `SamplePackageB-iOS` to bring in more kinds of `.xcframework` that help replicate our issue

---

With that, I am now able to compile the EX app target, but when the app launches, I see the following issue:

```bash
dyld[97467]: Library not loaded: @rpath/ogg.framework/ogg
  Referenced from: <2DA628EF-071C-33D8-AA00-7B1A3EBC3599> /Users/cstultz/Library/Developer/Xcode/DerivedData/EX-dvopbqpxtghxchfetmgezzfsuptf/Build/Products/Debug-iphonesimulator/opus.framework/opus
  Reason: tried: '/Users/cstultz/Library/Developer/Xcode/DerivedData/EX-dvopbqpxtghxchfetmgezzfsuptf/Build/Products/Debug-iphonesimulator/ogg.framework/ogg' (no such file), '/Users/cstultz/Library/Developer/Xcode/DerivedData/EX-dvopbqpxtghxchfetmgezzfsuptf/Build/Products/Debug-iphonesimulator/PackageFrameworks/ogg.framework/ogg' (no such file), '/Users/cstultz/Library/Developer/CoreSimulator/Devices/79B9F89A-CC2B-4846-BBA7-84E3AF0DBDA7/data/Containers/Bundle/Application/17870CCD-78D9-41F8-AEC7-90DE0A49E573/Frameworks/ogg.framework/ogg' (no such file), '/Users/cstultz/Library/Developer/Xcode/DerivedData/EX-dvopbqpxtghxchfetmgezzfsuptf/Build/Products/Debug-iphonesimulator/opus.framework/Frameworks/ogg.framework/ogg' (no such file), '/Users/cstultz/Library/Developer/CoreSimulator/Devices/79B9F89A-CC2B-4846-BBA7-84E3AF0DBDA7/data/Containers/Bundle/Application/17870CCD-78D9-41F8-AEC7-90DE0A49E573/EX.app/Frameworks/ogg.framework/ogg' (no such file), '/Users/cstultz/Library/Developer/CoreSimulator/Devices/79B9F89A-CC2B-4846-BBA7-84E3AF0DBDA7/data/Containers/Bundle/Application/17870CCD-78D9-41F8-AEC7-90DE0A49E573/EX.app/Frameworks/ogg.framework/ogg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21E213/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ogg.framework/ogg' (no such file)
```

---

And when attempting to compile the EXTests target, I am seeing a familiar issue again: `Missing required module 'ThirdPartyAdapter'`

![image](https://github.com/trinhngocthuyen/cocoapods-spm/assets/7268057/bc9f7936-2fa5-4ccf-a041-2da94eb8e6ea)

Get the latest changes on my fork (branch: `kalub92/hyphenated_module_name_bug`) here: https://github.com/kalub92/cocoapods-spm/commit/5e9695e3760e73f2d4fc328df342bb8928421d62

**Comment by kalub92** [comment] 2024-06-05 13:37
Hey @trinhngocthuyen - any update on the above issues?

**Comment by trinhngocthuyen** [comment] 2024-06-06 01:04
Srr I'm a bit occupied lately. Will look into it this weekend.

**Comment by kalub92** [comment] 2024-06-06 06:49
> Srr I'm a bit occupied lately. Will look into it this weekend.

Thank you! I really appreciate it. 😁

**Comment by trinhngocthuyen** [comment] 2024-06-08 08:45
@kalub92 I fixed the issue (with Firebase) mentioned in https://github.com/trinhngocthuyen/cocoapods-spm/issues/87#issuecomment-2141028614 in #97. Kindly check again.

Regarding the issue about `Library not loaded: @rpath/ogg.framework/ogg`, would you mind creating another dedicated issue for better tracking? Thank you!

**Comment by kalub92** [comment] 2024-06-09 13:28
@trinhngocthuyen Thank you – I've confirmed that with #97 I can install `Firebase` via `spm_pkg. Just raised a new issue for the `Library not loaded...` bug: https://github.com/trinhngocthuyen/cocoapods-spm/issues/98

Thanks again for all your hard work – this is going to really help my team once it's working for us!

**Comment by trinhngocthuyen** [comment] 2024-06-15 10:09
Gonna follow up on the other thread/issue. For this thread, I think I'm gonna close as it's becoming more irrelevant with the original (which was not the case).

**Closed by trinhngocthuyen** 2024-06-15 10:09 UTC
Labels: bug
